pipeline{    
    agent any   
    tool name: 'maven', type: 'maven'
    stages {
        stage ('Build Application'){
            steps {
                sh 'mvn clean package'
            }
            post {
                success {
                    echo 'Now Archiving the Artifacts'
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
    }   
}