pipeline{    
    agent any   
    tools {
        maven 'maven'
    }

    stages {
        stage ('Build Application'){
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo 'Now Archiving the Artifacts'
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage ('Deploy to Staging Environment') {
            steps{
                deploy adapters: [tomcat9(credentialsId: 'tomcat-staging-credentials', path: '', url: 'http://172.17.0.1:8888')], contextPath: '/', war: '**/*.war'
            }
            post {
                success {
                    echo 'Deployed on Staging Environment'
                }
            }
        }
    }   
}